// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CubicleDto
 */
export type CubicleDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Toilet Id
     */
    toilet_id: number;
    /**
     * Occupied
     */
    occupied?: boolean;
    /**
     * Toilet Roll Percentage
     */
    toilet_roll_percentage?: number;
};

/**
 * CubicleEventDto
 */
export type CubicleEventDto = {
    /**
     * Occupied
     */
    occupied: boolean;
    /**
     * Toilet Roll Percentage
     */
    toilet_roll_percentage: number;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CubicleEventListDto
 */
export type CubicleEventListDto = {
    /**
     * Cubicle Id
     */
    cubicle_id: number;
    /**
     * Events
     */
    events: Array<CubicleEventDto>;
};

/**
 * CubicleRequestDto
 */
export type CubicleRequestDto = {
    /**
     * Toilet Id
     */
    toilet_id: number;
};

/**
 * CubiclesListDto
 */
export type CubiclesListDto = {
    /**
     * Toilet Id
     */
    toilet_id: number;
    /**
     * Cubicles
     */
    cubicles: Array<CubicleDto>;
};

/**
 * FilteredCubicleEventDto
 */
export type FilteredCubicleEventDto = {
    period_range: PeriodRange;
    /**
     * Cubicle Id
     */
    cubicle_id: number;
    /**
     * Events
     */
    events: Array<CubicleEventDto>;
};

/**
 * FilteredMallEventDto
 */
export type FilteredMallEventDto = {
    period_range: PeriodRange;
    /**
     * Mall Id
     */
    mall_id: number;
    /**
     * Toilets
     */
    toilets: Array<ToiletEventDto>;
};

/**
 * FilteredToiletEventDto
 */
export type FilteredToiletEventDto = {
    period_range: PeriodRange;
    /**
     * Toilet Id
     */
    toilet_id: number;
    /**
     * Cubicles
     */
    cubicles: Array<CubicleEventListDto>;
};

/**
 * Gender
 */
export type Gender = 'male' | 'female' | 'unisex';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LatestCubicleStateDto
 */
export type LatestCubicleStateDto = {
    /**
     * Cubicle Id
     */
    cubicle_id: number;
    /**
     * Occupied
     */
    occupied: boolean;
    /**
     * Toilet Roll Percentage
     */
    toilet_roll_percentage: number;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LatestMallStateDto
 */
export type LatestMallStateDto = {
    /**
     * Mall Id
     */
    mall_id: number;
    /**
     * Toilets
     */
    toilets: Array<LatestToiletStateDto>;
};

/**
 * LatestToiletStateDto
 */
export type LatestToiletStateDto = {
    /**
     * Toilet Id
     */
    toilet_id: number;
    /**
     * Cubicles
     */
    cubicles: Array<LatestCubicleStateDto>;
};

/**
 * MallDto
 */
export type MallDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Toilets
     */
    toilets?: Array<ToiletDto>;
};

/**
 * MallRequestDto
 */
export type MallRequestDto = {
    /**
     * Name
     */
    name: string;
};

/**
 * PeriodRange
 */
export type PeriodRange = {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: unknown;
};

/**
 * ToiletDto
 */
export type ToiletDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Level
     */
    level: string;
    /**
     * Gender
     */
    gender: string;
    /**
     * Description
     */
    description: string;
    /**
     * Mall Id
     */
    mall_id: number;
};

/**
 * ToiletEventDto
 */
export type ToiletEventDto = {
    /**
     * Toilet Id
     */
    toilet_id: number;
    /**
     * Cubicles
     */
    cubicles: Array<CubicleEventListDto>;
};

/**
 * ToiletRequestDto
 */
export type ToiletRequestDto = {
    /**
     * Level
     */
    level: string;
    gender: Gender;
    /**
     * Description
     */
    description: string;
};

/**
 * ToiletsListDto
 */
export type ToiletsListDto = {
    /**
     * Mall Id
     */
    mall_id: number;
    /**
     * Toilets
     */
    toilets: Array<ToiletDto>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetMallsMallsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/malls/';
};

export type GetMallsMallsGetResponses = {
    /**
     * Response Get Malls Malls  Get
     *
     * Successful Response
     */
    200: Array<MallDto>;
};

export type GetMallsMallsGetResponse = GetMallsMallsGetResponses[keyof GetMallsMallsGetResponses];

export type CreateMallMallsPostData = {
    body: MallRequestDto;
    path?: never;
    query?: never;
    url: '/malls/';
};

export type CreateMallMallsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMallMallsPostError = CreateMallMallsPostErrors[keyof CreateMallMallsPostErrors];

export type CreateMallMallsPostResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type CreateMallMallsPostResponse = CreateMallMallsPostResponses[keyof CreateMallMallsPostResponses];

export type DeleteMallMallsMallIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type DeleteMallMallsMallIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMallMallsMallIdDeleteError = DeleteMallMallsMallIdDeleteErrors[keyof DeleteMallMallsMallIdDeleteErrors];

export type DeleteMallMallsMallIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteMallMallsMallIdDeleteResponse = DeleteMallMallsMallIdDeleteResponses[keyof DeleteMallMallsMallIdDeleteResponses];

export type GetMallMallsMallIdGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type GetMallMallsMallIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMallMallsMallIdGetError = GetMallMallsMallIdGetErrors[keyof GetMallMallsMallIdGetErrors];

export type GetMallMallsMallIdGetResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type GetMallMallsMallIdGetResponse = GetMallMallsMallIdGetResponses[keyof GetMallMallsMallIdGetResponses];

export type UpdateMallMallsMallIdPutData = {
    body: MallRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type UpdateMallMallsMallIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMallMallsMallIdPutError = UpdateMallMallsMallIdPutErrors[keyof UpdateMallMallsMallIdPutErrors];

export type UpdateMallMallsMallIdPutResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type UpdateMallMallsMallIdPutResponse = UpdateMallMallsMallIdPutResponses[keyof UpdateMallMallsMallIdPutResponses];

export type GetToiletsMallsMallIdToiletsGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/';
};

export type GetToiletsMallsMallIdToiletsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToiletsMallsMallIdToiletsGetError = GetToiletsMallsMallIdToiletsGetErrors[keyof GetToiletsMallsMallIdToiletsGetErrors];

export type GetToiletsMallsMallIdToiletsGetResponses = {
    /**
     * Successful Response
     */
    200: ToiletsListDto;
};

export type GetToiletsMallsMallIdToiletsGetResponse = GetToiletsMallsMallIdToiletsGetResponses[keyof GetToiletsMallsMallIdToiletsGetResponses];

export type CreateToiletMallsMallIdToiletsPostData = {
    body: ToiletRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/';
};

export type CreateToiletMallsMallIdToiletsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateToiletMallsMallIdToiletsPostError = CreateToiletMallsMallIdToiletsPostErrors[keyof CreateToiletMallsMallIdToiletsPostErrors];

export type CreateToiletMallsMallIdToiletsPostResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type CreateToiletMallsMallIdToiletsPostResponse = CreateToiletMallsMallIdToiletsPostResponses[keyof CreateToiletMallsMallIdToiletsPostResponses];

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteError = DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors[keyof DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors];

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteResponse = DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses[keyof DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses];

export type GetToiletMallsMallIdToiletsToiletIdGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type GetToiletMallsMallIdToiletsToiletIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToiletMallsMallIdToiletsToiletIdGetError = GetToiletMallsMallIdToiletsToiletIdGetErrors[keyof GetToiletMallsMallIdToiletsToiletIdGetErrors];

export type GetToiletMallsMallIdToiletsToiletIdGetResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type GetToiletMallsMallIdToiletsToiletIdGetResponse = GetToiletMallsMallIdToiletsToiletIdGetResponses[keyof GetToiletMallsMallIdToiletsToiletIdGetResponses];

export type UpdateToiletMallsMallIdToiletsToiletIdPutData = {
    body: ToiletRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutError = UpdateToiletMallsMallIdToiletsToiletIdPutErrors[keyof UpdateToiletMallsMallIdToiletsToiletIdPutErrors];

export type UpdateToiletMallsMallIdToiletsToiletIdPutResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutResponse = UpdateToiletMallsMallIdToiletsToiletIdPutResponses[keyof UpdateToiletMallsMallIdToiletsToiletIdPutResponses];

export type GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}/cubicles/';
};

export type GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetError = GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetErrors[keyof GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetErrors];

export type GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetResponses = {
    /**
     * Successful Response
     */
    200: CubiclesListDto;
};

export type GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetResponse = GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetResponses[keyof GetCubiclesMallsMallIdToiletsToiletIdCubiclesGetResponses];

export type CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostData = {
    body: CubicleRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}/cubicles/';
};

export type CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostError = CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostErrors[keyof CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostErrors];

export type CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostResponses = {
    /**
     * Successful Response
     */
    200: CubicleDto;
};

export type CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostResponse = CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostResponses[keyof CreateCubicleMallsMallIdToiletsToiletIdCubiclesPostResponses];

export type DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
        /**
         * Cubicle Id
         */
        cubicle_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}/cubicles/{cubicle_id}';
};

export type DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteError = DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteErrors[keyof DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteErrors];

export type DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteResponse = DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteResponses[keyof DeleteCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdDeleteResponses];

export type GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
        /**
         * Cubicle Id
         */
        cubicle_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}/cubicles/{cubicle_id}';
};

export type GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetError = GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetErrors[keyof GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetErrors];

export type GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetResponses = {
    /**
     * Successful Response
     */
    200: CubicleDto;
};

export type GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetResponse = GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetResponses[keyof GetCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdGetResponses];

export type UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutData = {
    body: CubicleRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
        /**
         * Cubicle Id
         */
        cubicle_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}/cubicles/{cubicle_id}';
};

export type UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutError = UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutErrors[keyof UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutErrors];

export type UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutResponses = {
    /**
     * Successful Response
     */
    200: CubicleDto;
};

export type UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutResponse = UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutResponses[keyof UpdateCubicleMallsMallIdToiletsToiletIdCubiclesCubicleIdPutResponses];

export type GetEventsEventsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id?: number | null;
        /**
         * Cubicle Id
         */
        cubicle_id?: number | null;
        /**
         * Start Date
         */
        start_date?: unknown;
        /**
         * End Date
         */
        end_date?: unknown;
    };
    url: '/events/';
};

export type GetEventsEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventsEventsGetError = GetEventsEventsGetErrors[keyof GetEventsEventsGetErrors];

export type GetEventsEventsGetResponses = {
    /**
     * Response Get Events Events  Get
     *
     * Successful Response
     */
    200: FilteredCubicleEventDto | FilteredToiletEventDto | FilteredMallEventDto;
};

export type GetEventsEventsGetResponse = GetEventsEventsGetResponses[keyof GetEventsEventsGetResponses];

export type GetLatestStateEventsLatestGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id?: number | null;
        /**
         * Cubicle Id
         */
        cubicle_id?: number | null;
    };
    url: '/events/latest';
};

export type GetLatestStateEventsLatestGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLatestStateEventsLatestGetError = GetLatestStateEventsLatestGetErrors[keyof GetLatestStateEventsLatestGetErrors];

export type GetLatestStateEventsLatestGetResponses = {
    /**
     * Response Get Latest State Events Latest Get
     *
     * Successful Response
     */
    200: LatestCubicleStateDto | LatestToiletStateDto | LatestMallStateDto;
};

export type GetLatestStateEventsLatestGetResponse = GetLatestStateEventsLatestGetResponses[keyof GetLatestStateEventsLatestGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];
