// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMallAnalyticsAnalyticsAggregationGetData, GetMallAnalyticsAnalyticsAggregationGetErrors, GetMallAnalyticsAnalyticsAggregationGetResponses, GetToiletRollMeanAnalyticsToiletRollMeanGetData, GetToiletRollMeanAnalyticsToiletRollMeanGetErrors, GetToiletRollMeanAnalyticsToiletRollMeanGetResponses, ReadRootAnalyticsGetData, ReadRootAnalyticsGetResponses, ReadRootGetData, ReadRootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 */
export const readRootAnalyticsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootAnalyticsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootAnalyticsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/analytics/',
    ...options
});

/**
 * Get Mall Analytics
 */
export const getMallAnalyticsAnalyticsAggregationGet = <ThrowOnError extends boolean = false>(options: Options<GetMallAnalyticsAnalyticsAggregationGetData, ThrowOnError>) => (options.client ?? client).get<GetMallAnalyticsAnalyticsAggregationGetResponses, GetMallAnalyticsAnalyticsAggregationGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/analytics/aggregation',
    ...options
});

/**
 * Get Toilet Roll Mean
 */
export const getToiletRollMeanAnalyticsToiletRollMeanGet = <ThrowOnError extends boolean = false>(options: Options<GetToiletRollMeanAnalyticsToiletRollMeanGetData, ThrowOnError>) => (options.client ?? client).get<GetToiletRollMeanAnalyticsToiletRollMeanGetResponses, GetToiletRollMeanAnalyticsToiletRollMeanGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/analytics/toilet-roll-mean',
    ...options
});

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/',
    ...options
});
