// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AggregationDto
 */
export type AggregationDto = {
    frequency: Frequency;
    period_range: PeriodRange;
    aggregation_level: AggregationLevel;
    /**
     * Aggregation
     */
    aggregation: Array<HourlyAggregationItem> | Array<DailyAggregationItem>;
    /**
     * Peak
     */
    peak?: string | null;
    /**
     * Lowest
     */
    lowest?: string | null;
};

/**
 * AggregationLevel
 */
export type AggregationLevel = 'mall' | 'toilet' | 'cubicle';

/**
 * DailyAggregationItem
 */
export type DailyAggregationItem = {
    /**
     * Occupied Count
     */
    occupied_count: number;
    /**
     * Day
     */
    day: string;
};

/**
 * DailyMeanPercentageItem
 */
export type DailyMeanPercentageItem = {
    /**
     * Mean Percentage
     */
    mean_percentage: number;
    /**
     * Day
     */
    day: string;
};

/**
 * Frequency
 */
export type Frequency = 'hour' | 'day';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HourlyAggregationItem
 */
export type HourlyAggregationItem = {
    /**
     * Occupied Count
     */
    occupied_count: number;
    /**
     * Hour
     */
    hour: string;
};

/**
 * HourlyMeanPercentageItem
 */
export type HourlyMeanPercentageItem = {
    /**
     * Mean Percentage
     */
    mean_percentage: number;
    /**
     * Hour
     */
    hour: string;
};

/**
 * MeanPercentageDto
 */
export type MeanPercentageDto = {
    frequency: Frequency;
    period_range: PeriodRange;
    /**
     * Mean Percentages
     */
    mean_percentages: Array<HourlyMeanPercentageItem> | Array<DailyMeanPercentageItem>;
    /**
     * Highest Mean Datetime
     */
    highest_mean_datetime: string | null;
    /**
     * Lowest Mean Datetime
     */
    lowest_mean_datetime: string | null;
};

/**
 * PeriodRange
 */
export type PeriodRange = {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootAnalyticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics/';
};

export type ReadRootAnalyticsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMallAnalyticsAnalyticsAggregationGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id?: number | null;
        /**
         * Cubicle Id
         */
        cubicle_id?: number | null;
        frequency?: Frequency;
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/analytics/aggregation';
};

export type GetMallAnalyticsAnalyticsAggregationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMallAnalyticsAnalyticsAggregationGetError = GetMallAnalyticsAnalyticsAggregationGetErrors[keyof GetMallAnalyticsAnalyticsAggregationGetErrors];

export type GetMallAnalyticsAnalyticsAggregationGetResponses = {
    /**
     * Successful Response
     */
    200: AggregationDto;
};

export type GetMallAnalyticsAnalyticsAggregationGetResponse = GetMallAnalyticsAnalyticsAggregationGetResponses[keyof GetMallAnalyticsAnalyticsAggregationGetResponses];

export type GetToiletRollMeanAnalyticsToiletRollMeanGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id?: number | null;
        /**
         * Cubicle Id
         */
        cubicle_id?: number | null;
        frequency?: Frequency;
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/analytics/toilet-roll-mean';
};

export type GetToiletRollMeanAnalyticsToiletRollMeanGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToiletRollMeanAnalyticsToiletRollMeanGetError = GetToiletRollMeanAnalyticsToiletRollMeanGetErrors[keyof GetToiletRollMeanAnalyticsToiletRollMeanGetErrors];

export type GetToiletRollMeanAnalyticsToiletRollMeanGetResponses = {
    /**
     * Successful Response
     */
    200: MeanPercentageDto;
};

export type GetToiletRollMeanAnalyticsToiletRollMeanGetResponse = GetToiletRollMeanAnalyticsToiletRollMeanGetResponses[keyof GetToiletRollMeanAnalyticsToiletRollMeanGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
