// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMallMallsPostData, CreateMallMallsPostErrors, CreateMallMallsPostResponses, CreateToiletMallsMallIdToiletsPostData, CreateToiletMallsMallIdToiletsPostErrors, CreateToiletMallsMallIdToiletsPostResponses, DeleteMallMallsMallIdDeleteData, DeleteMallMallsMallIdDeleteErrors, DeleteMallMallsMallIdDeleteResponses, DeleteToiletMallsMallIdToiletsToiletIdDeleteData, DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors, DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses, GetMallMallsMallIdGetData, GetMallMallsMallIdGetErrors, GetMallMallsMallIdGetResponses, GetMallsMallsGetData, GetMallsMallsGetResponses, GetToiletMallsMallIdToiletsToiletIdGetData, GetToiletMallsMallIdToiletsToiletIdGetErrors, GetToiletMallsMallIdToiletsToiletIdGetResponses, GetToiletsMallsMallIdToiletsGetData, GetToiletsMallsMallIdToiletsGetErrors, GetToiletsMallsMallIdToiletsGetResponses, RootGetData, RootGetResponses, UpdateMallMallsMallIdPutData, UpdateMallMallsMallIdPutErrors, UpdateMallMallsMallIdPutResponses, UpdateToiletMallsMallIdToiletsToiletIdPutData, UpdateToiletMallsMallIdToiletsToiletIdPutErrors, UpdateToiletMallsMallIdToiletsToiletIdPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Malls
 */
export const getMallsMallsGet = <ThrowOnError extends boolean = false>(options?: Options<GetMallsMallsGetData, ThrowOnError>) => (options?.client ?? client).get<GetMallsMallsGetResponses, unknown, ThrowOnError>({ url: '/malls/', ...options });

/**
 * Create Mall
 */
export const createMallMallsPost = <ThrowOnError extends boolean = false>(options: Options<CreateMallMallsPostData, ThrowOnError>) => (options.client ?? client).post<CreateMallMallsPostResponses, CreateMallMallsPostErrors, ThrowOnError>({
    url: '/malls/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Mall
 */
export const deleteMallMallsMallIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteMallMallsMallIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteMallMallsMallIdDeleteResponses, DeleteMallMallsMallIdDeleteErrors, ThrowOnError>({ url: '/malls/{mall_id}', ...options });

/**
 * Get Mall
 */
export const getMallMallsMallIdGet = <ThrowOnError extends boolean = false>(options: Options<GetMallMallsMallIdGetData, ThrowOnError>) => (options.client ?? client).get<GetMallMallsMallIdGetResponses, GetMallMallsMallIdGetErrors, ThrowOnError>({ url: '/malls/{mall_id}', ...options });

/**
 * Update Mall
 */
export const updateMallMallsMallIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateMallMallsMallIdPutData, ThrowOnError>) => (options.client ?? client).put<UpdateMallMallsMallIdPutResponses, UpdateMallMallsMallIdPutErrors, ThrowOnError>({
    url: '/malls/{mall_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Toilets
 */
export const getToiletsMallsMallIdToiletsGet = <ThrowOnError extends boolean = false>(options: Options<GetToiletsMallsMallIdToiletsGetData, ThrowOnError>) => (options.client ?? client).get<GetToiletsMallsMallIdToiletsGetResponses, GetToiletsMallsMallIdToiletsGetErrors, ThrowOnError>({ url: '/malls/{mall_id}/toilets/', ...options });

/**
 * Create Toilet
 */
export const createToiletMallsMallIdToiletsPost = <ThrowOnError extends boolean = false>(options: Options<CreateToiletMallsMallIdToiletsPostData, ThrowOnError>) => (options.client ?? client).post<CreateToiletMallsMallIdToiletsPostResponses, CreateToiletMallsMallIdToiletsPostErrors, ThrowOnError>({
    url: '/malls/{mall_id}/toilets/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Toilet
 */
export const deleteToiletMallsMallIdToiletsToiletIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteToiletMallsMallIdToiletsToiletIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses, DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors, ThrowOnError>({ url: '/malls/{mall_id}/toilets/{toilet_id}', ...options });

/**
 * Get Toilet
 */
export const getToiletMallsMallIdToiletsToiletIdGet = <ThrowOnError extends boolean = false>(options: Options<GetToiletMallsMallIdToiletsToiletIdGetData, ThrowOnError>) => (options.client ?? client).get<GetToiletMallsMallIdToiletsToiletIdGetResponses, GetToiletMallsMallIdToiletsToiletIdGetErrors, ThrowOnError>({ url: '/malls/{mall_id}/toilets/{toilet_id}', ...options });

/**
 * Update Toilet
 */
export const updateToiletMallsMallIdToiletsToiletIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateToiletMallsMallIdToiletsToiletIdPutData, ThrowOnError>) => (options.client ?? client).put<UpdateToiletMallsMallIdToiletsToiletIdPutResponses, UpdateToiletMallsMallIdToiletsToiletIdPutErrors, ThrowOnError>({
    url: '/malls/{mall_id}/toilets/{toilet_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
