// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Gender
 */
export type Gender = 'male' | 'female' | 'unisex';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MallDto
 */
export type MallDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Toilets
     */
    toilets?: Array<ToiletDto>;
};

/**
 * MallRequestDto
 */
export type MallRequestDto = {
    /**
     * Name
     */
    name: string;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: unknown;
};

/**
 * ToiletDto
 */
export type ToiletDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Level
     */
    level: string;
    /**
     * Gender
     */
    gender: string;
    /**
     * Description
     */
    description: string;
    /**
     * Mall Id
     */
    mall_id: number;
};

/**
 * ToiletRequestDto
 */
export type ToiletRequestDto = {
    /**
     * Level
     */
    level: string;
    gender: Gender;
    /**
     * Description
     */
    description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetMallsMallsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/malls/';
};

export type GetMallsMallsGetResponses = {
    /**
     * Response Get Malls Malls  Get
     *
     * Successful Response
     */
    200: Array<MallDto>;
};

export type GetMallsMallsGetResponse = GetMallsMallsGetResponses[keyof GetMallsMallsGetResponses];

export type CreateMallMallsPostData = {
    body: MallRequestDto;
    path?: never;
    query?: never;
    url: '/malls/';
};

export type CreateMallMallsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMallMallsPostError = CreateMallMallsPostErrors[keyof CreateMallMallsPostErrors];

export type CreateMallMallsPostResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type CreateMallMallsPostResponse = CreateMallMallsPostResponses[keyof CreateMallMallsPostResponses];

export type DeleteMallMallsMallIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type DeleteMallMallsMallIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMallMallsMallIdDeleteError = DeleteMallMallsMallIdDeleteErrors[keyof DeleteMallMallsMallIdDeleteErrors];

export type DeleteMallMallsMallIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteMallMallsMallIdDeleteResponse = DeleteMallMallsMallIdDeleteResponses[keyof DeleteMallMallsMallIdDeleteResponses];

export type GetMallMallsMallIdGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type GetMallMallsMallIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMallMallsMallIdGetError = GetMallMallsMallIdGetErrors[keyof GetMallMallsMallIdGetErrors];

export type GetMallMallsMallIdGetResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type GetMallMallsMallIdGetResponse = GetMallMallsMallIdGetResponses[keyof GetMallMallsMallIdGetResponses];

export type UpdateMallMallsMallIdPutData = {
    body: MallRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}';
};

export type UpdateMallMallsMallIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMallMallsMallIdPutError = UpdateMallMallsMallIdPutErrors[keyof UpdateMallMallsMallIdPutErrors];

export type UpdateMallMallsMallIdPutResponses = {
    /**
     * Successful Response
     */
    200: MallDto;
};

export type UpdateMallMallsMallIdPutResponse = UpdateMallMallsMallIdPutResponses[keyof UpdateMallMallsMallIdPutResponses];

export type GetToiletsMallsMallIdToiletsGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/';
};

export type GetToiletsMallsMallIdToiletsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToiletsMallsMallIdToiletsGetError = GetToiletsMallsMallIdToiletsGetErrors[keyof GetToiletsMallsMallIdToiletsGetErrors];

export type GetToiletsMallsMallIdToiletsGetResponses = {
    /**
     * Response Get Toilets Malls  Mall Id  Toilets  Get
     *
     * Successful Response
     */
    200: Array<ToiletDto>;
};

export type GetToiletsMallsMallIdToiletsGetResponse = GetToiletsMallsMallIdToiletsGetResponses[keyof GetToiletsMallsMallIdToiletsGetResponses];

export type CreateToiletMallsMallIdToiletsPostData = {
    body: ToiletRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/';
};

export type CreateToiletMallsMallIdToiletsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateToiletMallsMallIdToiletsPostError = CreateToiletMallsMallIdToiletsPostErrors[keyof CreateToiletMallsMallIdToiletsPostErrors];

export type CreateToiletMallsMallIdToiletsPostResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type CreateToiletMallsMallIdToiletsPostResponse = CreateToiletMallsMallIdToiletsPostResponses[keyof CreateToiletMallsMallIdToiletsPostResponses];

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteError = DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors[keyof DeleteToiletMallsMallIdToiletsToiletIdDeleteErrors];

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteToiletMallsMallIdToiletsToiletIdDeleteResponse = DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses[keyof DeleteToiletMallsMallIdToiletsToiletIdDeleteResponses];

export type GetToiletMallsMallIdToiletsToiletIdGetData = {
    body?: never;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type GetToiletMallsMallIdToiletsToiletIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToiletMallsMallIdToiletsToiletIdGetError = GetToiletMallsMallIdToiletsToiletIdGetErrors[keyof GetToiletMallsMallIdToiletsToiletIdGetErrors];

export type GetToiletMallsMallIdToiletsToiletIdGetResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type GetToiletMallsMallIdToiletsToiletIdGetResponse = GetToiletMallsMallIdToiletsToiletIdGetResponses[keyof GetToiletMallsMallIdToiletsToiletIdGetResponses];

export type UpdateToiletMallsMallIdToiletsToiletIdPutData = {
    body: ToiletRequestDto;
    path: {
        /**
         * Mall Id
         */
        mall_id: number;
        /**
         * Toilet Id
         */
        toilet_id: number;
    };
    query?: never;
    url: '/malls/{mall_id}/toilets/{toilet_id}';
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutError = UpdateToiletMallsMallIdToiletsToiletIdPutErrors[keyof UpdateToiletMallsMallIdToiletsToiletIdPutErrors];

export type UpdateToiletMallsMallIdToiletsToiletIdPutResponses = {
    /**
     * Successful Response
     */
    200: ToiletDto;
};

export type UpdateToiletMallsMallIdToiletsToiletIdPutResponse = UpdateToiletMallsMallIdToiletsToiletIdPutResponses[keyof UpdateToiletMallsMallIdToiletsToiletIdPutResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];
