import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IdProvider } from "@/context/IdContext";

import { client as availClient } from './services/availability/client.gen';
import { client as analyticsClient } from './services/analytics/client.gen';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    availClient.setConfig({
      baseUrl: 'http://iot-backend-alb-227826614.ap-southeast-1.elb.amazonaws.com',
    });

    analyticsClient.setConfig({
      baseUrl: 'http://iot-backend-alb-227826614.ap-southeast-1.elb.amazonaws.com',
    });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IdProvider>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <SidebarTrigger />
                {children}
          </main>
        </SidebarProvider>
        </IdProvider>
      </body>
    </html>
  );
}
